platform :ios, '15.0'

target 'RunningOS' do
  use_frameworks!

  # AMap SDKs
  pod 'AMapFoundationKit'
  pod 'AMap3DMap'
  pod 'MAMapKit'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
